### ISSUE TITLE
小米5手机报内存溢出

### ISSUE THREAD

**Issue by dejianpu** [qiyukf/react-native-qiyu#7]
java.lang.OutOfMemoryError: Failed to allocate a 2560012 byte allocation with 843048 free bytes and 823KB until OOM
 at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
 at android.graphics.Bitmap.nativeCreate(Native Method)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:890)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:867)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:834)
 at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
 at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
 at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
 at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.createBitmapInternal(ArtBitmapFactory.java:62)
 at com.facebook.imagepipeline.request.BasePostprocessor.process(BasePostprocessor.java:60)
 at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.postprocessInternal(PostprocessorProducer.java:252)
 at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.doPostprocessing(PostprocessorProducer.java:220)
 at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.access$600(PostprocessorProducer.java:78)
 at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer$2.run(PostprocessorProducer.java:178)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
 at java.lang.Thread.run(Thread.java:761)

**Comment by wangchenyan** [comment]
@dejianpu 你好，这个看起来是fresco的错误
